services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_vector_db
    ports:
      - "5433:5432" # Cổng máy thật : container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'nckh@HTN'
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: